using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using DashBoardTest01.Permissions;
using DashBoardTest01.Dashboards;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using DashBoardTest01.Shared;

namespace DashBoardTest01.Dashboards
{
    public class DashboardsAppService : DashboardsAppServiceBase, IDashboardsAppService
    {
        //<suite-custom-code-autogenerated>
        public DashboardsAppService(IDashboardRepository dashboardRepository, DashboardManager dashboardManager, IDistributedCache<DashboardExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(dashboardRepository, dashboardManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}