FROM mcr.microsoft.com/dotnet/aspnet:8.0  AS base
COPY bin/Release/net8.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p d3da2a36-2877-4d8e-985b-d301aaa7368d

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "DashBoardTest01.HttpApi.Host.dll"]