using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace DashBoardTest01.Dashboards
{
    public class DashboardManager : DashboardManagerBase
    {
        //<suite-custom-code-autogenerated>
        public DashboardManager(IDashboardRepository dashboardRepository)
            : base(dashboardRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}